[build]
  command = "yarn build"
  functions = "lambda"
  publish = "build"
[context.deploy-preview.environment]
  REACT_APP_WORKSHOPCHALLENGE_API_ENDPOINT = "https://hackshackondemand.hpedev.io"
[context.staging.environment] # 'staging' is a branch name
  REACT_APP_WORKSHOPCHALLENGE_API_ENDPOINT = "https://hackshackondemand.hpedev.io"
[context.testing.environment]
  REACT_APP_WORKSHOPCHALLENGE_API_ENDPOINT = "https://hackshackdevtest.hpedev.io"

[[redirects]]
from = "https://deploy-preview-260--musing-kalam-f76e20.netlify.app"
to = "https://pr-927.d2wz01xj8bm9sl.amplifyapp.com/hackshack"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
