[build]
  command = "yarn build"
  functions = "lambda"
  publish = "build"
[context.deploy-preview.environment]
  REACT_APP_WORKSHOPCHALLENGE_API_ENDPOINT = "https://hackshackondemand.hpedev.io"
[context.staging] # 'staging' is a branch name
  REACT_APP_WORKSHOPCHALLENGE_API_ENDPOINT = "https://hackshackondemand.hpedev.io"