[build]
  command = "yarn build"
  functions = "lambda"
  publish = "build"
[context.deploy-preview.environment]
  REACT_APP_WORKSHOPCHALLENGE_API_ENDPOINT = "https://hackshackondemand.hpedev.io"
[context.staging.environment] # 'staging' is a branch name
  REACT_APP_WORKSHOPCHALLENGE_API_ENDPOINT = "https://hackshackchallenge.hpedev.io"
[context.jay/wod-revamp.environment]
  REACT_APP_CHALLENGE_API_ENDPOINT = "http://hackshackdevtest.hpe.io:8082"